---
- hosts: instafap_*
  pre_tasks:
    - name: Update APT Repository
      apt: update_cache=yes
  roles:
    - name: instafap
  vars:
    - projects:
      - instafap-db
      - instafap-api
      - instafap-client
      - instafap-ws
      - instafap
