---
- include: deps.yml
- name: "Restarting RethinkDB"
  service:
    name=rethinkdb
    state=restarted
- name: "Copying Projects"
  copy:
    src="instafap-db"
    dest=/opt/
    mode=u=r,g=r
- name: "Running npm install"
  command: bash -c "npm install || npm install"
    chdir="/opt/instafap-db"
    creates="/opt/instafap-db/node_modules"
- name: "Setting up Database"
  command: bash -c "node setup.js"
    chdir="/opt/instafap-db"
